name: github-pages

on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment

jobs:
  publish:
    name: Deploy Site
    runs-on: ubuntu-22.04
    environment: github-pages
    steps:
      - name: Install Latex
        shell: bash
        run: |
          sudo apt install texlive-full

      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install packages
        shell: bash
        run: |
          pip install --user -r dockers/requirements.txt

      - name: Make PDF
        shell: bash
        run: |
          make latexpdf
          cp build/latex/*.pdf source/_static/
          rm -rf build/latex

      - name: Make Html
        shell: bash
        run: |
          sphinx-build -b html source build

      - name: Deploy Website
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
